# Generated by Django 5.0.1 on 2024-01-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Administrador', 'Admin'), ('Administrador Academia', 'Gerente Academia'), ('Funcionário Academia', 'Funcionario Academia'), ('Cliente Academia', 'Cliente Academia')], max_length=50)),
                ('academy_id', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
