# Generated by Django 4.2.3 on 2024-01-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('Administrador Sistema', 'Administrador Sistema'), ('Administrador Academia', 'Gerente Academia'), ('Funcionário Academia', 'Funcionario Academia'), ('Cliente Academia', 'Cliente Academia')], max_length=50),
        ),
    ]
